import Hero from "@/components/hero/Hero";
import Showcase from "@/components/showcase/Showcase";
import { ShowcaseArticle } from "@/lib/CONSTANTS";

const TASKS_HERO_COPY = {
    title: "Tasks & Study Plan",
    subtitle:
        "Gentle study suggestions generated by ReedAI based on your learning activity. Stay organized without the pressure.",
    cta: [
        { label: "See My Tasks", href: "#", variant: "btn-blue" },
    ],
};

const TASKS_ARTICLES: ShowcaseArticle[] = [
    {
        id: 1,
        icon: "https://placehold.co/96x96/2EC4B6/FFF?text=Focus",
        title: "Stay Focused",
        isNew: true,
        desc: "Know exactly what to revise next and focus on your weak areas.",
        href: "#",
    },
    {
        id: 2,
        icon: "https://placehold.co/96x96/1E2A5E/FFF?text=Flex",
        title: "Flexible",
        isNew: false,
        desc: "Tasks are optional and adaptable. No streaks specifically designed to stress you out.",
        href: "#",
    },
];

export default function TasksPage() {
    return (
        <main>
            <Hero copy={TASKS_HERO_COPY} variant="centered" />
            <Showcase
                articles={TASKS_ARTICLES}
                quote="Stay organized without pressure."
                author="— Study Plans"
            />
        </main>
    );
}
